name: Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.1
        with:
          cmake-version: "3.28.3"

      - name: Install OpenCV
        id: install_opencv
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev

      - name: Install GTest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -B build -S .
          cmake --build build
          sudo cmake --install build

      - name: Create Build Directory
        run: mkdir -p build
        shell: bash

      - name: Build
        run: |
          cmake -B build -S .
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
